### ISSUE TITLE
Disable pylint: file-not-used for csv files

### ISSUE THREAD

**Issue by maitaoriana** [Vauxoo/pylint-odoo#133]
In some cases the data of the `csv` files are loaded from a hook then it is not necessary to add it to the `__manifest__.py ` file.

But this pylint error occurs:
`[W7930 (file-not-used),] not used from manifest`

**Comment by moylop260** [comment]
What is your real case?

NOTE: If you use `tests` folder the check is skipped

**Comment by maitaoriana** [comment]
@moylop260  In this PR https://github.com/Vauxoo/mexico/pull/870, i have two csv files ([l10n_mx_edi.res.locality.csv](https://github.com/vauxoo-dev/enterprise/blob/17934b3994cc1c8825a907f5eb60e0bcb1c2c269/l10n_mx_edi_external_trade/data/l10n_mx_edi.res.locality.csv), [res.city.csv](https://github.com/vauxoo-dev/enterprise/blob/17934b3994cc1c8825a907f5eb60e0bcb1c2c269/l10n_mx_edi_external_trade/data/res.city.csv)) and they are not uset from manifest because they are loaded from hook. 

These files contain the data of the cities and localities of Mexico, do you think it is correct to move them to the tests folder?

**Comment by moylop260** [comment]
@maitaoriana I saw the docstring of your method `Import CSV data as it is faster than xml and because we can't use noupdate anymore with csv`

 - Using csv is faster than xml
 - Using hook allow you don't update the data for each `-u module`

So we need to support this case, maybe a extra folder defined for this cases...

@JesusZapata 
Could you help us to support a extra folder for these cases?

(I don't know what is the better name but maybe @nhomar could help us to define a folder name)

**Comment by nhomar** [comment]
@moylop260 we can not ignore the file itself? why a folder? and remember this is how this is working on 11.0 also in all case use static folder ?

**Comment by maitaoriana** [comment]
@moylop260, are you agree with add the files in static folder?

**Comment by moylop260** [comment]
- We can not ignore the file because the csv don't accept comments.
- The files are heavy to use static folder.

Maybe, we should use the folder `examples` defined in our template module in order to skip these cases:
 - https://github.com/OCA/maintainer-tools/tree/master/template/module/examples

**Comment by maitaoriana** [comment]
@moylop260 Any news about this? Remember this is still pending.

**Comment by egrivero** [comment]
@moylop260 about this issue is there any progress?, is that for vauxoo/mexico 11.0, only this is needed to correct the lint. If you need something help with tests, I can support you with that.

**Comment by luisg123v** [comment]
@moylop260 
I've got a couple of ideas in mint to solve this issue:
- Since this are data files, but they're not loaded as usual, they could be located into a folder named `data_extra`, similar to how the translations folder is named in [this module](https://github.com/Vauxoo/mexico/tree/10.0/l10n_mx_reports/i18n_extra).
- They could also be located into a `.gz` file, so the file name would be something like `res.city.csv.gz`. Of course, files would need to be extracted before being imported, but (IMO) this approach is more consistent with large data files like these.

What do you think?
