### ISSUE TITLE
pylint not detecting tabs and duplicated ids in xml files

### ISSUE THREAD

**Issue by JVegaB** [Vauxoo/pylint-odoo#152]
Steps to reproduce
===============
- Run pylint in https://git.vauxoo.com/vauxoo/xunnel-account/blob/11.0/account_xunnel/demo/account_journals.xml

Expected
=======
- test failing because of duplicated ids in Odoo records and containing tabs instead of spaces

Saw
===
- Nothing failing

**Comment by moylop260** [comment]
Is not related with gitlab environment variables @luisg123v ?

**Comment by moylop260** [comment]
@JVegaB 
Could you add the MR or project where is not showing the tabs and xml_id duplicated lints?

**Comment by moylop260** [comment]
Fixed from:
https://git.vauxoo.com/vauxoo/xunnel-account/merge_requests/52

**Comment by luisg123v** [comment]
Just for the record, I created a dummy MR to reproduce the issue, performing a `git checkout` on the aforementioned file to use a failing version:  
https://git.vauxoo.com/vauxoo/xunnel-account/merge_requests/50

After the fix, the dummy MR changed from green to red.

The issue was not caused by Pylint, but by an incomplete set-up in the `.travis.yml` file.
