### ISSUE TITLE
error| end-of-line within string [po/msgfmt]

### ISSUE THREAD

**Issue by luistorresm** [Vauxoo/pylint-odoo#176]
Avoid missing end line in po file.

In the next case: 
![Screen Shot 2020-12-02 at 23 26 22](https://user-images.githubusercontent.com/7606656/100967835-d4fe4e80-34f5-11eb-9837-b2caa2537cb3.png)

The CI is a false green

**Comment by fernandahf** [comment]
Hi @luistorresm 

The .po file shown, ¿is it in an Odoo module?

Regards.

**Comment by fernandahf** [comment]
After researching, we found that issue comes from polib library, polib does not detect the missing quote, even it cuts msgstr as following example shows:

![Screen Shot 2021-04-16 at 17 11 43](https://user-images.githubusercontent.com/54731581/115088927-d6de1280-9ed6-11eb-857e-44be7cd46962.png)

![Screen Shot 2021-04-16 at 17 08 42](https://user-images.githubusercontent.com/54731581/115088719-6e8f3100-9ed6-11eb-9673-24a690716169.png)

We searched other libraries that can help but don't found any.

I will close this issue, so problem is other library.

**Comment by moylop260** [comment]
It was not possible to do it
