### ISSUE TITLE
[ADD] missing-depend: Use of xml_id without depends

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/pylint-odoo#29]
A `module_child.xml_id` was used in `module_parent`  where the depends tree don't exists `module_child`

We have the following [issue](https://github.com/Vauxoo/yoytec/issues/1163) and [this one](https://github.com/Vauxoo/yoytec/issues/1228)

We need a new check to detect early this common issue.
However, for this check we will need a full git clone of `oca_dependencies.txt` to get all recursive depends...

Then CI build of `LINT=1` don't have all recursive depends.
The CI build of `TESTS=1` have all recursive depends but don't run lint checks.

Then we will need a way to run just this lint check for TESTS=1 environment...

FYI 
- [x] Code to get all depends of a odoo module: [get_depends()](https://github.com/Vauxoo/maintainer-quality-tools/blob/db1ff2d6b0c1d9e5de80b1934cc34f2240b0b689/travis/getaddons.py#L107-L112)
- [x] Code to get all xml_id of a odoo module: [get_xml_record_ids()](https://github.com/Vauxoo/pylint-odoo/blob/ab6601dc3152e77250eaf5be025ec8495fed5d75/pylint_odoo/misc.py#L205-L211)
- [ ] Code to fusion all depends and all xml_id of a odoo module. (Final result of this issue)
- [ ] Consider the case where a demo xml_id is used in data/data ref.

**Comment by LuisAlejandro** [comment]
Cool, working on it ASAP.

**Comment by LuisAlejandro** [comment]
What we can do is to check if an xml_id like [the one](https://github.com/Vauxoo/yoytec/blob/05d0a7a0fde649524c766f448ccf64d3304e2b63/yoytec_supplier_rma_workflow/reports/reports.xml#L5) on vauxoo/yoytec#1163 does have its dependency listed in the manifest file. As simple as:

report.xml
```
<report id="[MODULE].[ID]"
```
Is [MODULE] listed in manifest file?
No > FAIL
YES > PASS

But in that case we don't need to clone the oca dependencies, or do we?

I don't know if i understood the problem correctly. If the problem is that a module referenced by a report is not listed in the manifest, then the check is very simple.

If the problem is that the ID of a module no longer exists, then another check should be made:

report.xml
```
<report id="[MODULE].[ID]"
```
Does [MODULE] has [ID]?
No > FAIL
YES > PASS

And, furthermore, one should be able to specify a version for the depends in the manifest file. So that if an [ID] disappears or changes name in a version, then one can say "this depends on version NN that has [ID]". I think this also leads to the discussion on OCA, IMHO, odoo modules should be python packages.

**Comment by moylop260** [comment]
Consider the following:
- module_a
 - `__openerp__.py`
  - depends: module_b
- module_b
 - `__openerp__.py`
  - depends: module_c
- module_c

The module_c create the xml_id: `module_c.xml_id_01`
The module_a use a reference to `module_c.xml_id_01` then works! Fail: No, Pass: Yes
Because the full depends tree have access to `module_c` from `module_a`

**Comment by moylop260** [comment]
@LuisAlejandro
I'll take this issue

**Comment by moylop260** [comment]
Fixed from https://github.com/Vauxoo/server-tools/pull/41/files
